# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1fde27306d54a02ff494390383b9996a8067be2145a5f39a87e571bb3674a53f8b51587da9dd1cb6064952b95becea2a14fc59d6f8ccb1bb0a36aa6156c5c11

test:
  secret_key_base: 57d458a60a92f0a4322fd50437b48d3fb6f395dd97536f3d476a0e012921eb444cd57cac45b508656d80c10a930f549f8dbbcb3acf2e6d920f7105effb4a181d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
